### ISSUE TITLE
Baixar conteúdo inteiro

### ISSUE THREAD

**Issue by antrologos** [meirelesff/rscielo#1]
Muito legal, Fernando.  Você pensa em adicionar funções para baixar o conteúdo completo?

**Comment by antrologos** [comment]
Uma possibilidade seria isso aqui:

```
get_articleContent <- function(url){
        
        page    <- rvest::html_session(url)
        
        text <- rvest::html_nodes(page, xpath = "//div[@id='article-body']")
        text <- rvest::html_text(text)
        
        foot_notes <- rvest::html_nodes(page, xpath = "//div[@class='fn']")
        foot_notes <- rvest::html_text(foot_notes)
        foot_notes <- stringr::str_replace_all(foot_notes, pattern = "[\n|\t|\r]", replacement = "")
        
        references <- rvest::html_nodes(page, xpath = "//p[@class='ref']")
        references <- rvest::html_text(references)
        references <- stringr::str_replace_all(references, pattern = "[\n|\t|\r]", replacement = "")
        references <- stringr::str_replace_all(references, pattern = "[\\[][[:blank:]+]Links[[:blank:]+][\\]]", replacement = "")
        
        articleContent <- list(text       = text, 
                               foot_notes = foot_notes,
                               references = references)
        
        articleContent
}
```

**Comment by meirelesff** [comment]
Valeu, Rogério! É uma boa ideia, com certeza. Na verdade, criei esse pacote há bastante tempo pra resolver um problema específico, e depois acabei deixando ele de lado. Até fiquei surpreso que ele ainda funciona. Talvez seja uma boa ideia atualizá-lo e submetê-lo ao CRAN, incluindo essa funcionalidade. Posso usar esse código como base para essa função -- te colocando, obviamente, como colaborador?

**Comment by antrologos** [comment]
Olá Fernando,

A idéia parece muito boa. Não sei se mereço ser colaborador... hahaha.... mas podemos tentar sim.

Seguinte: descobri que há pelo menos dois padrões bem diferentes de HTML no Scielo. Provavelmente, o código que eu escrevi acima apenas funcionam com os textos colocados mais recentemente na plataforma, que possivelmente já foram inseridos por meio de um aplicativo (CMS) mais estruturado (talvez cada parte do texto e dos metadados foram colocados por meio de formulários, com campos específicos). 

Mas existe um padrão mais antigo, que não diferencia corpo do texto, de notas, referências etc. Tudo está marcado simplesmente com a Tag <p> no html. Então outras estratégias de identificação e separação do conteúdo têm que ser usadas. 

Escrevi um código porco e mal organizado aqui... mas que (acho que) faz o trabalho. Não testei muito, mas pelo que pude perceber funciona. Basicamente a função get_articleContent tenta coletar o artigo pelo método acima. Se não rolar, ela chama uma outra, que foi feita para o padrão de formatação antigo. Fiz correndo e não elaborei ainda uma estratégia para coletar as notas de pé de página. Mas dê uma olhada aí. 


```
get_articleContent <- function(url){
        
        page    <- rvest::html_session(url)
        text <- rvest::html_nodes(page, xpath = "//div[@id='article-body']")
        text <- rvest::html_text(text)
        
        if(length(text)==0) {
                articleContent <- get_articleContent_old(page)
        }else{
                #foot_notes <- rvest::html_nodes(page, xpath = "//div[@class='fn']")
                #foot_notes <- rvest::html_text(foot_notes)
                #foot_notes <- stringr::str_replace_all(foot_notes, pattern = "[\n|\t|\r]", replacement = "")
                
                references <- rvest::html_nodes(page, xpath = "//p[@class='ref']")
                references <- rvest::html_text(references)
                references <- stringr::str_replace_all(references, pattern = "[\n|\t|\r]", replacement = "")
                references <- stringr::str_replace_all(references, pattern = "[\\[][[:blank:]+]Links[[:blank:]+][\\]]", replacement = "")
                
                articleContent <- list(text       = text, 
                                       #foot_notes = foot_notes,
                                       references = references)
        }
        
        articleContent
}



get_articleContent_old <- function(page){
        
        nodes <- page %>% 
                rvest::html_nodes(xpath = "//div[@class='content']/div/p|//div[@class='content']/div/p/preceding-sibling::comment()|//div/hr")
        
        tag_names <- purrr::map(nodes, rvest::html_tag) %>% 
                unlist()
        
        nodes = nodes[(dplyr::last(which(tag_names=="hr"))+1):length(nodes)]
        
        complete_content    <- rvest::html_text(nodes)
        references_location <- which(complete_content == " ref ")
        
        text       <- complete_content[1:(first(references_location) - 2)]
        references <- complete_content[(references_location + 1)]
        
        articleContent = list(text       = paste(text, collapse = " "),
                              references = references)
        
        articleContent
}
```

**Comment by meirelesff** [comment]
Boa, Rogério! Se não me engano, quando criei as principais funções do pacote também encontrei um problema parecido pra pegar o número de referências usadas em cada artigo. Cheguei a coletar dados de todos os periódicos do Scielo e mesmo em outros campos ficaram erros, como na autoria e filiação institucional.

Acho que o jeito é testar essa função atualizada assim, em todos os periódicos, pra ver se funciona. Talvez eu faça um profiling dela ante só pra ver se é possível ganhar tempo em alguma coisa, e aí depois eu subo ela e já inicio uma nova versão do pacote (vou te deixar como colaborador no repo, aí tu pode ficar mais à vontade pra modificar e atualizar o código simultaneamente).
