### ISSUE TITLE
Error on function "get_journal()'

### ISSUE THREAD

**Issue by beatrizmilz** [meirelesff/rscielo#3]
Hello! This package is very interesting, but when I use the function get_journal it returns an error. 

Olá! Achei o pacote muito interessante, porém não consigo usar a função get_journal(). Segue o código e também o erro. 

`library(rScielo)`

`id_journal <- get_id_journal("http://www.scielo.br/scielo.php?script=sci_serial&pid=1414-753X&lng=en&nrm=iso")`

`meta_journal <- get_journal(id_journal)`

**Error message/mensagem de erro:**
> Warning in format.data.frame(x, trim = TRUE, drop0trailing = TRUE, ...) :
  corrupt data frame: columns will be truncated or padded with NAs

Obrigada! Thank you.

**Comment by beatrizmilz** [comment]
I tested the function get_article() and it results only with a vector of NA'S.

**Comment by meirelesff** [comment]
Obrigado pelo feedback, @beatrizmilz. A verdade é que esse pacote foi desenvolvido há um tempo e, desde então, não foi mais atualizado. Eu e o @antrologos estamos pensando em fazer isso agora, dando mais funcionalidades a ele. Na próxima versão, vou checar esse e outros possíveis erros.

**Comment by beatrizmilz** [comment]
Entendi! O pacote é muito interessante, parabéns pelo trabalho de vocês!
Consegui baixar dados sobre os artigos da revista através do Scielo de outra forma, porém vem com apenas algumas informações (título, ano, autores). Pelo que li no readme, no pacote conseguiria mais informações.
@antrologos Quando você tenta usar essas funções, funciona normalmente?
